# Tensor operations

This notebook implements the following operations with tensors of in Numpy:

- Addition
- Scalar multiplication
- Outer product
- Inner product
- Contraction
- Broadcasting

## Addition (and subtraction)

Tensor addition operations are on a entry level of the same shape.

In [15]:
import numpy as np
SEED = 9999

In [ ]:
A = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
print(A.shape)
A

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
np.random.seed(SEED)
B = np.random.randint(1, 4, (2, 2, 2))
B

array([[[3, 2],
        [3, 2]],

       [[2, 3],
        [2, 1]]])

In [18]:
A + B

array([[[4, 4],
        [6, 6]],

       [[7, 9],
        [9, 9]]])

## Scalar multiplication

Likewise, scalar multiplication is also applied on an entry level.

In [ ]:
c = 2
c * A

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]]])

In [21]:
print(A * c == c * A) # also commutative

[[[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


In [ ]:
c * (A + B) # also distrbutative

array([[[ 8,  8],
        [12, 12]],

       [[14, 18],
        [18, 18]]])

## Outer product

In tensor operations, the outer product is roughly thought of as a generalization of the Kronecker product. The key difference being, the rank of a tensor outer product is the sum of the tensor ranks of its factors while the Kronecker product remains a rank 2 tensor (ie a matrix) and expands in size.


In [ ]:
X = [[1, 2], [3, 4]] # rank 2 tensor of (2, 2)

outer_product = np.multiply.outer(X, B)
outer_product.shape

(np.multiply.outer(X, B) == np.multiply.outer(B, X))[0,0,0] # the outer product is not communitative

array([[ True, False],
       [False, False]])

In [28]:
B

array([[[3, 2],
        [3, 2]],

       [[2, 3],
        [2, 1]]])

In [27]:
outer_product[0, 0, 0]

array([[3, 2],
       [3, 2]])

Note the outer_product's (1,1,1,1,1) entry is a product of X at (1,1) and B at (1,1,1) and its (1,1,1,1,2) entry is the product of X at (1,1) and B at (1,1,2).

In [30]:
outer_product[1,0,0]

array([[9, 6],
       [9, 6]])

Note the outer_product's (2,1,1,1,1) entry is a product of X at (2,1) and B at (1,1,1) and its (2,1,1,1,2) entry is the product of X at (2,1) and B at (1,1,2).

In conclusion, the entries of the outer product between `X` and `B` is summarized in the following statement:

$$
    product_{ijklm} = x_{ij} \times b_{klm} 
$$

where the outer product is of the shape (2,2,2,2,2).

## Inner product

The inner product between 2 tensors is a product between 2 tensors where dimension(s) of the same length of each factor is chosen to be aggregated.
The inputs of a tensor inner product operation thus requires 2 tensors AND dimension(s) intended for aggregation

In [47]:
inner_product = np.tensordot(X, B, axes=(0, 0))
inner_product

array([[[ 9, 11],
        [ 9,  5]],

       [[14, 16],
        [14,  8]]])

Note that the size of the inner product is now (2,2,2) instead of (2,2,2,2,2) like the outer product. This is because when we chose the 1st axes of X and B to be aggregated the rank has collapsed. In this particular case, the entries of the inner product tensor is illustrated by the following:

$$
    product_{jkm} = \sum_{i=1}^{2} x_{ij} \cdot b_{ikm}
$$

meaning the inner product's entry at (1,1,1) = 1x3 + 3x2 = 9

## Contractions

In fact, we can aggregate and collapse dimensions in a given tensor in the same fashion. These operations are call contractions. And requires a given tensors and dimensions it needs to be aggregated on.

In [55]:
# The best way to implement tensor contraction is via np.einsum function where the string entry denotes first denotes the index of each dimension 
# with the arrow pointing to which dimension should be remaining after the contraction.

np.einsum("ijk->ij", A)

array([[ 3,  7],
       [11, 15]])

In the above code where the 3rd dimension is contracted, it could be summarized as:

$$
    contracted_{ij} = \sum_{k=1}^{2} a_{ijk}
$$

Where the entry at (1,1) is A at (1, 1, 1) + A at (1, 1, 2)

In [57]:
np.einsum("ijk->ik", A)

array([[ 4,  6],
       [12, 14]])

Similarly, when contracting at the 2nd dimension, the resulting entry at (1,1) is A at (1,1,1) + A at (1, 2, 1) (i.e 1 + 3).

In [58]:
np.einsum("ijk->jk", A)

array([[ 6,  8],
       [10, 12]])

Again, when contracting at the 1st dimension, the resulting entry at (1,1) is A at (1,1,1) + A at (2, 1, 1) (i.e 1 + 5).

## Broadcasting

Broadcasting is an operations used in calculation packages to enable element-wise operations (ex addition) between 2 tensors of different ranks. It essentially just stretches (or pads) the smaller tensor/scalar to a matching dimension then adds them together.

Note that this is not exactly a standard operation used in tensor calculus or differential geometry.

In [61]:
X

[[1, 2], [3, 4]]

In [62]:
B

array([[[3, 2],
        [3, 2]],

       [[2, 3],
        [2, 1]]])

In [63]:
X + B

array([[[4, 4],
        [6, 6]],

       [[3, 5],
        [5, 5]]])

The above example, the rank 2 tensor X is transformed into a rank 3 tensor with (2, 2, 2) shape where the original rank 2 tensor is duplicated in the first dimension to add to rank 3 tensor B.