# Machine Learning with PyTorch

This notebook is used to understand how to implement SGD with PyTorch before experimenting with other algorithms.

In [1]:
# test if pytorch is working
import torch
torch.__version__

'2.7.0.dev20250128+cpu'

## Data Wranggling

PyTorch works with Tensor objects. Operations of Tensors behave like Numpy arrays and can be passed back and forth.

In [24]:
a = torch.tensor(1)
print(a)

b = torch.tensor([1, 2])
print(b)

tensor(1)
tensor([1, 2])


In [25]:
X = torch.tensor([[1,2],[3,4]])
Y = torch.tensor([[5,6],[7,8]])

print(X + Y)
print(X * Y)
print(X @ Y)

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
print(X.dim()) #dimensions
print(b.dim())
print(a.dim())

print("---")

print(X.ndim)
print(b.ndim)
print(a.ndim)

2
1
0
---
2
1
0


In [ ]:
u = torch.tensor([3, 4])
v = torch.tensor([2, 3])

torch.dot(u, v) # dot product

tensor(18)

In [ ]:
try:
    torch.dot(X, Y) # doesn't work because dot products only works on vectors
except Exception as e:
    print(e)

1D tensors expected, but got 2D and 2D tensors


In [ ]:
print(X.T) #transpose matrix

tensor([[1, 3],
        [2, 4]])


### Dealing with Numpy

PyTorch tensors can go hand to hand with Numpy arrays

In [32]:
import numpy as np

print(X.numpy())
type(X.numpy())

[[1 2]
 [3 4]]


numpy.ndarray

In [34]:
print(torch.from_numpy(np.array([[4,5],[6,7]])))
type(torch.from_numpy(np.array([[4,5],[6,7]])))

tensor([[4, 5],
        [6, 7]])


torch.Tensor

## Working with GPUs

In [35]:
# detect whether CUDA is available

print(f"is CUDA available: {torch.cuda.is_available()}")

# detect whether silicon GPU is available

print(f"is apple silicon available: {torch.backends.mps.is_available()}")

is CUDA available: False
is apple silicon available: False


Tensors can be moved to GPUs using `TENSOR.to(device = "cuda")` or `TENSOR.to(device = "mps")`.

Note that once a tensor is in a GPU, it cannot be exported to Numpy.

## OLS with PyTorch

Below is code to create a simple OLS model with PyTorch.

In [36]:
from torch import nn

In [ ]:
# mock regression data

weight = 0.77
bias = 0.28

