# Doing Linear Algebra with Numpy

In [1]:
import numpy as np

# Numpy data types

## Arrays

Although matrices exist in Numpy, they are on their way to be deprecated. All non-scalar operations should be done with arrays.
Below are different ways of creating arrays.

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim) #dimensions of array = this means the number of "axes" an array has and not the dimension of the matrix itself
print(arr[0]) #0-based index
arr

<class 'numpy.ndarray'>
(5,)
5
1
1


array([1, 2, 3, 4, 5])

In [3]:
# in linear algebra terms

row_vector = np.array([[1],[2],[3]])
print(row_vector)
print(row_vector.shape)
column_vector = np.array([[1,2,3]])
print(column_vector)
print(column_vector.shape)

[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)


In [4]:
arr = np.array(42)
print(type(arr))
print(arr.shape)
# print(len(arr)) - this will give an error because the arr is 0-dimension!
print(arr.ndim)
arr

<class 'numpy.ndarray'>
()
0


array(42)

In [5]:
arr = np.array([42])
print(type(arr))
print(arr.shape)
print(len(arr)) # this is fine because it is an array with length 1 since list was entered
print(arr.ndim)
arr

<class 'numpy.ndarray'>
(1,)
1
1


array([42])

Let's create the following matrix as a numpy array:

$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
        5 & 6 \\
    \end{pmatrix}
$$

In [7]:
arr = np.array([[1,2],[3, 4],[5, 6]]) # first array for columns, 2nd array for row (column vector of row vectors)
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0]) #0 based indexing 
arr

<class 'numpy.ndarray'>
(3, 2)
3
2
3


array([[1, 2],
       [3, 4],
       [5, 6]])

Now let's make a 3 dimensional numpy array (tensor).

In [8]:
arr = np.array([[[1,2],[3, 4]],[[5,6],[7,8]]])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0,1]) #0 based indexing 
print(arr.size) #number of scalar entries in an array
arr

<class 'numpy.ndarray'>
(2, 2, 2)
2
3
6
8


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
# more on indexing

print(arr[0]) #this takes the 1st matrix out of the 3-d array from before
print("--")
print(arr[1,1]) #this takes the 2nd row of the 2nd matrix

[[1 2]
 [3 4]]
--
[7 8]


### Special vectors and matrices

In [10]:
# diagonal matrix
diag = np.diag([1,2,3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [93]:
# identity matrix
id = np.identity(3)
print(id)
id2 = np.eye(2)
print(id2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [94]:
# incrementing
print(np.arange(4))
print(np.arange(2, 9, 2)) #from 2 to 9, skip by 2
print(np.linspace(0, 20, num = 5)) #can do even splits between a range (in this case 0 to 20, give 5 evenly spaced values)

[0 1 2 3]
[2 4 6 8]
[ 0.  5. 10. 15. 20.]


In [95]:
print(np.ones((2,3), dtype=np.int64)) # array of ones
print(np.zeros((2,3))) # array of 0s

[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]]


### Operating within the array

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concat((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concat((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
# converting 1D arrays to 2

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
row_vector = a[np.newaxis, :]
print(row_vector.shape)
column_vector = a[:, np.newaxis]
print(column_vector.shape)


(6,)
(1, 6)
(6, 1)


In [101]:
#alternatives
column_vector = np.expand_dims(a, axis=1)
print(column_vector)
print(column_vector.shape)
row_vector = np.expand_dims(a, axis=0)
print(row_vector)
print(row_vector.shape)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 2 3 4 5 6]]
(1, 6)


In [103]:
# combining/concatenating matrices together

a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

print(np.vstack((a1,a2)))
print("---")
print(np.hstack((a1,a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
---
[[1 1 3 3]
 [2 2 4 4]]


In [91]:
# split a column vector out
A = np.hstack((a1,a2))

y = A[:,-1]
X = A[:,:-1]

print(X)
print(y)

[[1 1 3]
 [2 2 4]]
[3 4]


# Linear algebra operations

## Addition

In [25]:
# vectors (1-d array)

a = np.arange(3)
b = np.ones(3)

print(a)
print(b)
a + b

[0 1 2]
[1. 1. 1.]


array([1., 2., 3.])

In [27]:
# matrices (2-d array)

a = np.arange(6).reshape(2,3)
b = np.ones(6).reshape(2,3)
print(a)
print(b)
a + b

[[0 1 2]
 [3 4 5]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
# tensors (3d+ array)

a = np.arange(18).reshape(2,3,3)
b = np.ones(18).reshape(2,3,3)
print(a)
print(b)
a + b


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [30]:
# when dimensions don't match
a = np.arange(6).reshape(3,2)
b = np.ones(6).reshape(2,3)
try:
    a + b
except Exception as e:
    print(f"ERROR: {e}")

ERROR: operands could not be broadcast together with shapes (3,2) (2,3) 


### Summing over axis of rows or columns

In [31]:
a = np.arange(15).reshape(3,5)
print(a)
a.sum(axis = 0) # sum over columns (returns a vector)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([15, 18, 21, 24, 27])

In [32]:
a.sum(axis = 1) # sum access over rows (returns a vector)

array([10, 35, 60])

## Multiplication

In [44]:
# element wise multiplication (Hadamard product)

A = np.arange(4).reshape(2,2)
B = np.arange(4).reshape(2,2)

print(A * B)
print(A ** 3)

[[0 1]
 [4 9]]
[[ 0  1]
 [ 8 27]]


In [47]:
# matrix product

A = np.arange(6).reshape(2,3)
B = np.arange(6).reshape(3,2)
print(A)
print(B)
A @ B

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


array([[10, 13],
       [28, 40]])

In [36]:
# dot product
v = np.arange(4)
w = np.array([5,6,7,8])

print(np.dot(v, w))
v.dot(w)

44


np.int64(44)

In [37]:
# cross product
v = np.arange(3)
w = np.array([6,7,8])

np.cross(v, w)

array([-6, 12, -6])

## Other manipulations

In [38]:
# transpose
a = np.arange(6).reshape(2,3)
print(a)
print(a.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [39]:
# inverse
a = np.linspace(1, 4, num = 4).reshape(2,2)
print(a)
np.linalg.inv(a)

[[1. 2.]
 [3. 4.]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
# pseudo-inverse
b = np.linspace(1, 6, num = 6).reshape(2,3)
np.linalg.pinv(b)

array([[-0.94444444,  0.44444444],
       [-0.11111111,  0.11111111],
       [ 0.72222222, -0.22222222]])

In [41]:
# determinant
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [42]:
# eigenvalues
print(np.linalg.eigvals(a))
# eigenvalues and eigenvectors
print(np.linalg.eig(a))
print(np.linalg.eig(np.diag([1,2,3])))

[-0.37228132  5.37228132]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
EigResult(eigenvalues=array([1., 2., 3.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [43]:
# matrix rank
np.linalg.matrix_rank(a)

np.int64(2)

In [77]:
# filtering out blanks

y = np.array([1,2,np.nan,4, np.nan, 5,7,19])
y[~np.isnan(y)]

array([ 1.,  2.,  4.,  5.,  7., 19.])

In [92]:
# filter out rows with at least 1 blank
X = np.array([1,2,np.nan,4, np.nan, 5,7,19]).reshape(4,2)
print(X)
X[~np.isnan(X).any(axis = 1)]

[[ 1.  2.]
 [nan  4.]
 [nan  5.]
 [ 7. 19.]]


array([[ 1.,  2.],
       [ 7., 19.]])

In [86]:
# filter out columns with at least 1 blank
X = np.array([1,2,np.nan,4, np.nan, 5,7,19]).reshape(4,2)
print(X)
X.T[~np.isnan(X.T).any(axis = 1)].T

[[ 1.  2.]
 [nan  4.]
 [nan  5.]
 [ 7. 19.]]


array([[ 2.],
       [ 4.],
       [ 5.],
       [19.]])