# Doing Linear Algebra with Numpy

In [1]:
import numpy as np

# Numpy data types

## Arrays

Although matrices exist in Numpy, they are on their way to be deprecated. All non-scalar operations should be done with arrays.
Below are different ways of creating arrays.

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim) #dimensions of array
print(arr[0]) #0-based index
arr

<class 'numpy.ndarray'>
(5,)
5
1
1


array([1, 2, 3, 4, 5])

In [3]:
arr = np.array(42)
print(type(arr))
print(arr.shape)
# print(len(arr)) - this will give an error because the arr is 0-dimension!
print(arr.ndim)
arr

<class 'numpy.ndarray'>
()
0


array(42)

In [4]:
arr = np.array([42])
print(type(arr))
print(arr.shape)
print(len(arr)) # this is fine because it is an array with length 1 since list was entered
print(arr.ndim)
arr

<class 'numpy.ndarray'>
(1,)
1
1


array([42])

Let's create the following matrix as a numpy array:

$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
    \end{pmatrix}
$$

In [5]:
arr = np.array([[1,2],[3, 4]]) # first array for columns, 2nd array for row (column vector of row vectors)
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[0,1]) #0-based index for matrix
arr

<class 'numpy.ndarray'>
(2, 2)
2
2
2


array([[1, 2],
       [3, 4]])

Let's create the following matrix as a numpy array:

$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
        5 & 6 \\
    \end{pmatrix}
$$

In [6]:
arr = np.array([[1,2],[3, 4],[5, 6]]) # first array for columns, 2nd array for row (column vector of row vectors)
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0]) #0 based indexing 
arr

<class 'numpy.ndarray'>
(3, 2)
3
2
3


array([[1, 2],
       [3, 4],
       [5, 6]])

Now let's make a 3 dimensional numpy array (tensor).

In [7]:
arr = np.array([[[1,2],[3, 4]],[[5,6],[7,8]]])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0,1]) #0 based indexing 
arr

<class 'numpy.ndarray'>
(2, 2, 2)
2
3
6


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
# more on indexing

print(arr[0]) #this takes the 1st matrix out of the 3-d array from before
print(arr[1,1]) #this takes the 2nd row of the 2nd matrix

[[1 2]
 [3 4]]
[7 8]
