# Doing Linear Algebra with Numpy

In [1]:
import numpy as np

# Numpy data types

## Arrays

Although matrices exist in Numpy, they are on their way to be deprecated. All non-scalar operations should be done with arrays.
Below are different ways of creating arrays.

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim) #dimensions of array = this means the number of "axes" an array has and not the dimension of the matrix itself
print(arr[0]) #0-based index
arr

<class 'numpy.ndarray'>
(5,)
5
1
1


array([1, 2, 3, 4, 5])

In [3]:
arr = np.array(42)
print(type(arr))
print(arr.shape)
# print(len(arr)) - this will give an error because the arr is 0-dimension!
print(arr.ndim)
arr

<class 'numpy.ndarray'>
()
0


array(42)

In [4]:
arr = np.array([42])
print(type(arr))
print(arr.shape)
print(len(arr)) # this is fine because it is an array with length 1 since list was entered
print(arr.ndim)
arr

<class 'numpy.ndarray'>
(1,)
1
1


array([42])

Let's create the following matrix as a numpy array:

$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
    \end{pmatrix}
$$

In [5]:
arr = np.array([[1,2],[3, 4]]) # first array for columns, 2nd array for row (column vector of row vectors)
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[0,1]) #0-based index for matrix
arr

<class 'numpy.ndarray'>
(2, 2)
2
2
2


array([[1, 2],
       [3, 4]])

Let's create the following matrix as a numpy array:

$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
        5 & 6 \\
    \end{pmatrix}
$$

In [6]:
arr = np.array([[1,2],[3, 4],[5, 6]]) # first array for columns, 2nd array for row (column vector of row vectors)
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0]) #0 based indexing 
arr

<class 'numpy.ndarray'>
(3, 2)
3
2
3


array([[1, 2],
       [3, 4],
       [5, 6]])

Now let's make a 3 dimensional numpy array (tensor).

In [19]:
arr = np.array([[[1,2],[3, 4]],[[5,6],[7,8]]])
print(type(arr))
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr[1,0,1]) #0 based indexing 
print(arr.size) #number of scalar entries in an array
arr

<class 'numpy.ndarray'>
(2, 2, 2)
2
3
6
8


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
# more on indexing

print(arr[0]) #this takes the 1st matrix out of the 3-d array from before
print("--")
print(arr[1,1]) #this takes the 2nd row of the 2nd matrix

[[1 2]
 [3 4]]
--
[7 8]


### Special vectors and matrices

In [14]:
# diagonal matrix
diag = np.diag([1,2,3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
# identity matrix
id = np.identity(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# incrementing
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(2, 9, 2) #from 2 to 9, skip by 2

array([2, 4, 6, 8])

In [22]:
np.linspace(0, 20, num = 5) #can do even splits between a range (in this case 0 to 20, give 5 evenly spaced values)

array([ 0.,  5., 10., 15., 20.])

In [27]:
np.ones((2,3), dtype=np.int64) # arrays of ones

array([[1, 1, 1],
       [1, 1, 1]])

### Operating within the array

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concat((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concat((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# converting 1D arrays to 2

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
row_vector = a[np.newaxis, :]
print(row_vector.shape)
col_vector = a[:, np.newaxis]
print(col_vector.shape)


(6,)
(1, 6)
(6, 1)


In [38]:
#alternatives
col_vector = np.expand_dims(a, axis=1)
print(col_vector.shape)
row_vector = np.expand_dims(a, axis=0)
print(row_vector.shape)


(6, 1)
(1, 6)


In [40]:
# combining/concatenating matrices together

a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [41]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Linear algebra operations

## Addition and subtraction

In [45]:
# vectors (1-d array)

a = np.arange(3)
b = np.ones(3)

print(a)
print(b)
a + b

[0 1 2]
[1. 1. 1.]


array([1., 2., 3.])

In [46]:
a - b

array([-1.,  0.,  1.])

In [47]:
# matrices (2-d array)

a = np.arange(6).reshape(2,3)
b = np.ones(6).reshape(2,3)
print(a)
print(b)
a + b

[[0 1 2]
 [3 4 5]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
a - b

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [49]:
# tensors

a = np.arange(18).reshape(2,3,3)
b = np.ones(18).reshape(2,3,3)
print(a)
print(b)
a + b


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [50]:
# when dimensions don't match
a = np.arange(6).reshape(3, 2)
b = np.ones(6).reshape(2,3)

a + b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 